### ISSUE TITLE
problem with deno sample on https://repl.it/@balupton/caterpillar-deno#index.ts

### ISSUE THREAD

**Issue by stefano77it** [bevry/caterpillar#130]
running the sample from https://repl.it/@balupton/caterpillar-deno#index.ts with deno (version 1.4.2) I receive the error

```
error: Import 'https://unpkg.com/rfc-log-levels@3.14.0/edition-deno/index.ts' failed: 404 Not Found
Imported from "https://unpkg.com/caterpillar@6.5.0/edition-deno/logger.ts:1"
```

a solution was to import the library not with unpkg.com but with jspm.dev
```
import { Logger, Filter, Human } from 'https://jspm.dev/caterpillar'
```
or skypack.dev
```
import { Logger, Filter, Human } from 'https://cdn.skypack.dev/caterpillar'
```

In this way the sample works perfectly

**Comment by balupton** [comment]
Thanks for the heads up. Will get around to fix this up properly in the coming days.

**Comment by balupton** [comment]
so tracked it down, `make-deno-edition` is not failing to compile:

```
necessary entry file [/Users/balupton/Projects/caterpillar/source/index.ts] failed
↳  has import incompatibilities
  ↳  internal import of [./logger.js] => [./logger.ts]
    ↳  import of local file [./logger.js] has incompatibilities
  ↳  internal import of [./transforms/filter.js] => [./transforms/filter.ts]
    ↳  import of local file [./transforms/filter.js] has incompatibilities
  ↳  internal import of [./transforms/human.js] => [./transforms/human.ts]
    ↳  import of local file [./transforms/human.js] has incompatibilities

optional utility file [/Users/balupton/Projects/caterpillar/source/logger.ts] skipped
↳  has import incompatibilities
  ↳  dep import of [rfc-log-levels] => [https://unpkg.com/rfc-log-levels@^3.14.0/edition-esnext/index.js]
    ↳  resolved to [rfc-log-levels/edition-esnext/index.js], which does not have the .ts extension
```

seems `rfc-log-levels` is not having a typescript edition published anymore, will look into it

**Comment by balupton** [comment]
so it failing for this reason:

```
> npx make-deno-edition
npx: installed 37 in 2.996s
make-deno-edition: UNEXEPCTED FAILURE!

Unable to make the deno edition, due to this unexpected error:
Error: require package.json file to be present
    at new Errlop (/Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/node_modules/errlop/edition-es5/index.js:61:18)
    at /Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/edition-esnext/index.js:310:4
    at async Object.make (/Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/edition-esnext/index.js:308:14)
    at async bin (/Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/edition-esnext/bin.js:54:19)
↳ Error: ENOENT: no such file or directory, open '/Users/balupton/Projects/auto/package.json' {
  klass: [Function: Errlop] {
    create: [Function (anonymous)],
    isErrlop: [Function (anonymous)],
    ensure: [Function (anonymous)]
  },
  parent: [Error: ENOENT: no such file or directory, open '/Users/balupton/Projects/auto/package.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/Users/balupton/Projects/auto/package.json'
  },
  ancestors: [
    [Error: ENOENT: no such file or directory, open '/Users/balupton/Projects/auto/package.json'] {
      errno: -2,
      code: 'ENOENT',
      syscall: 'open',
      path: '/Users/balupton/Projects/auto/package.json'
    }
  ],
  exitCode: -2,
  orphanStack: 'Error: require package.json file to be present\n' +
    '    at new Errlop (/Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/node_modules/errlop/edition-es5/index.js:61:18)\n' +
    '    at /Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/edition-esnext/index.js:310:4\n' +
    '    at async Object.make (/Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/edition-esnext/index.js:308:14)\n' +
    '    at async bin (/Users/balupton/.cache/npm/_npx/36226/lib/node_modules/make-deno-edition/edition-esnext/bin.js:54:19)'
}
```

which I'm surprised by, if someone can look into this, that would be great

**Comment by balupton** [comment]
so it is failing for this reason:

```
> npx make-deno-edition
make-deno-edition: FAILURE!

The required deno edition could not be created for the following reasons:

necessary entry file [/Users/balupton/Projects/auto/rfc-log-levels/source/index.ts] failed
↳  has import incompatibilities
  ↳  dep import of [rfc-log-levels] => [undefined]
    ↳  appears to be an uninstalled dependency, install it and try again

optional test file [/Users/balupton/Projects/auto/rfc-log-levels/source/test.ts] skipped
↳  has import incompatibilities
  ↳  dep import of [kava] => [https://unpkg.com/kava@^5.13.0/source/index.js]
    ↳  resolved to [kava/source/index.js], which does not have the .ts extension
  ↳  internal import of [./index.js] => [./index.ts]
    ↳  import of local file [./index.js] has incompatibilities
```

which is probably due to this:

https://github.com/bevry/rfc-log-levels/blob/f4761e552b643292e6262d8c80f347eaac1c5289/source/index.ts#L75

which I believe we have fixed a few times already

**Comment by balupton** [comment]
also figured out another contributing factor, the deno editions won't be getting generated on CI as deno doesn't exist there, so the unpkg and surge URLs for them do not exist, despire the readme file being generated on my local machine where Deno and consequently those compile targets do exist

Solution for this is installing Deno on the CI
