### ISSUE TITLE
Getting Error while running on Browser using vite package manager

### ISSUE THREAD

**Issue by funcbind** [bevry/caterpillar#287]
App - 

**Logger Instantiation Code**

```javascript
import { Logger, Human, Browser } from 'caterpillar';

// Caterpillar logger
const cLogger = new Logger();
cLogger.pipe(new Human()).pipe(new Browser());

cLogger.log('warn', 'this is a warning, which is level', 4);
cLogger.warn('this is a warning, which is level', 4);
``` 

**Error On Console**

```javascript
browser-external:util:9 Module "util" has been externalized for browser compatibility. Cannot access "util.inspect" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:util:9

human.js:72 Uncaught (in promise) TypeError: (0 , import_util.inspect) is not a function
    at human.js:72:15
    at Array.map (<anonymous>)
    at Human.formatArguments (human.js:70:14)
    at Human.format (human.js:105:24)
    at Human.write (transform.js:28:27)
    at transform.js:38:32
``` 

**Package.json File Contents**

```javascript
{
  "name": "vite-react-zustand-tryout",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "auto-zustand-selectors-hook": "^2.0.0",
    "caterpillar": "^8.2.0",
    "immer": "^10.1.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "zustand": "^4.5.2"
  },
  "devDependencies": {
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-plugin-react": "^7.34.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.6",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "vite": "^5.2.0"
  }
}

```

**Comment by balupton** [comment]
Hrmmm, seems inspect needs to be removed from the browser bundle. Thanks for the detailed log. Not sure when I will get to this, could be a few months from now. If it's important for your company, the work can be funded to make it a priority.

**Comment by molleweide** [comment]
I got similar issues when trying to use caterpillar as well in vite/react
